---
apiVersion: hoprnet.org/v1alpha2
kind: IdentityHoprd
metadata:
  name: ronny-rotsee-1
  namespace: core-team
spec:
  identityPoolName: team-rotsee
  identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiIzZmY1NDk4MGU1YWNkZmE3OTE1YTRmYjc0NDI2MGFlYyJ9LCJjaXBoZXJ0ZXh0IjoiZDBhYTUyOTE2YWExYjVlMDZmNDZiMGQ5ZWRkMTQzZDJhYmZjMGE5NDVjYmQ5NWZmOTk3OGRiNjUwMTI5NGFkZTZkMTFjM2NmN2QzNmYyNWZiNTIwYzhjZWE2NDM3N2JlNGM4Y2YyOGIyZDZjNWE1NGEzZTIwMWExY2IzOGQyMmNiOTFjMTMxZWE0YjJlMWYxMTdjYTgyYTRhZWZlMTlkMDM1M2RhZjdmZWM5Y2FjODdkMmVhNTUxYTJkZjNjZTI1MTIwY2NmYTljMTViOWY5OGEwYjlkODk3YWYzY2RjYzc2ZDc5YmI4OGFhNzY1ZDhmZTE4NTJiMmMwMzkwM2M4NjNmMDdlYzQ1NjdhYThjYmUwZGExYzVhZTQ0MGFhNzBkNmQyZWE0ODg2NGU0NDk4NmI4NzE4NDRmZGUyZTU0MDM2MTlhN2FkYTRjZWM4ZTkwNmZmZDdjNzAiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiYjAxN2QyNzRkOGQyMmY2MWFkYTg1MTA3OWJlYjFmYjc1MzIxZGM5M2E4M2ExMDY1MGVlZWEzZTJiZGUzZmI4NCJ9LCJtYWMiOiIxZTg4YmE1NWIxYjhhNWFlOTBhYzBhZDAwMDNkNmRiNDM3MzM4ZjE3YzQ5ODVkMjZhODk3NGVkMWIxMzEzNDUxIn0sImlkIjoiOWYwNWNjYWEtZWI1ZC00YmUyLWI5NTMtNTNmYTQ2NDQ3OWNlIiwidmVyc2lvbiI6M30="
  peerId: "12D3KooWHbVArTizMtJfKMHFyeuX46KCXXEYhsq1hTRayaP3kJXR"
  nativeAddress: "0x865dde9e5bf75a18e79273ca87dafef61a96479a"
  safeAddress: "0x0CDecAFf277C296665f31aAC0957a3A3151B6159"
  moduleAddress: "0x2031b4494500E7b112342741EFA5f61b2d8E6331"
---
apiVersion: hoprnet.org/v1alpha2
kind: Hoprd
metadata:
  name: ronny-1
  namespace: core-team
spec:
  version: 2.0.8
  identityPoolName: team-rotsee
  identityName: ronny-rotsee-1
  supportedRelease: providence
  enabled: true
  config: |
          host:
            address: !IPv4 0.0.0.0
            port: 9091
          identity:
            file: "/app/hoprd-db/.hoprd.id"
            password: "<REDACTED>"
            private_key:
          db:
            data: "/app/hoprd-db"
            initialize: true
            force_initialize: false
          inbox:
            capacity: 512
            max_age: 900
            excluded_tags:
            - 0
          api:
            enable: true
            auth: !Token "<REDACTED>"
            host:
              address: !IPv4 0.0.0.0
              port: 3001
          strategy:
            on_fail_continue: true
            allow_recursive: false
            finalize_channel_closure: true
            strategies:
              - !Aggregating
                aggregation_threshold: 300
                unrealized_balance_ratio: 0.9
                aggregation_timeout: 60
                aggregate_on_channel_close: true
              - !AutoRedeeming
                redeem_only_aggregated: True
          heartbeat:
            variance: 2000
            interval: 20000
            threshold: 60000
          network_options:
            min_delay: 1
            max_delay: 300
            quality_avg_window_size: 25
            quality_bad_threshold: 0.2
            quality_offline_threshold: 0.5
            quality_step: 0.1
            ignore_timeframe: 600
            backoff_exponent: 1.5
            backoff_min: 2
            backoff_max: 300
          healthcheck:
            enable: true
            host: 0.0.0.0
            port: 8080
          protocol:
            ack:
              timeout: 15
            heartbeat:
              timeout: 15
            msg:
              timeout: 15
            ticket_aggregation:
              timeout: 15
          network: rotsee
          chain:
            announce: true
            provider: https://primary.gnosis-chain.rpc.hoprtech.net
            check_unrealized_balance: true
          safe_module:
            safe_transaction_service_provider:
            safe_address:
              addr:
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
            module_address:
              addr:
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
                - 44
          test:
            announce_local_addresses: false
            prefer_local_addresses: false
            use_weak_crypto: false
