---
apiVersion: hoprnet.org/v1alpha2
kind: IdentityHoprd
metadata:
  name: tibor-dufour-1
  namespace: core-team
spec:
  identityPoolName: team-dufour
  identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJhYWVmZDBhZjQ5OTlkMmZmM2MyMDVhZjJmMDVhNjVjMyJ9LCJjaXBoZXJ0ZXh0IjoiOGJhNTIwMWM1MmZhOWQ5MWE0OGUzZTUyNTY4OTg2YjI3ZGYyOGNlN2I0YzFkMDcxOTAzOTY0NzEwYzhiOThjMDkyNDcwZTJkOWQ2MTg2M2E3ZDkyNGZlMGUxN2I4MzZkNDliOGQyNTkzNDA2NGE3Yjc1YmUwOTNjODdkOTc5ZGM5YTFhZTg2ZGYxYTIzZjU3OGVhNzAxNjhkMDUzMjUxMjg5NzY4NjZmZGFkNDQzY2M2OGEwMzc4OWZjNWJiZDZmM2I3Mzc3N2U2ODI5MGE4YTgyZGJlMzExMmZjNDg0MmRiYmUxOTZhZWY3ODg0NTgxNDVlYzM0NzRhZjU4NGE5ODkwMWIyNjdjMzEyZWMwYmE3OGE4MzA4NjMyMmE3MjAwODFlYTg0ZmJiMzc5YTM2YWI2MDhlNmI1NjJjNmNkZTQ3YTg1NmNiZjVkZmE2Nzc1MGM3OTU3YzciLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiN2QzMDQyNjYyOGFhN2I0NDUzYTE4NzIzYmE1MjA0ZGQwZThkOWVmYjgxYmNlNDNlYjk1MDhjYTZjMDYwZjdjOCJ9LCJtYWMiOiIxNzlhMTk5YjM2NmRiYzQ2MjU2ZTZkOTQ2YzM4YjU3MjQyODJmNGRmZmFjMTMzNjc0NDMwYWI3MmYxOWZjYzhiIn0sImlkIjoiZjkyMTVlYzMtNDEyZi00MjA0LWI1ZjAtODEyMjJhZGY3NWZiIiwidmVyc2lvbiI6M30="
  peerId: "12D3KooWCXHCRKu4iieq57NdRk4dtYU9GAPJSaj7qrmsDyTmLsog"
  nativeAddress: "0x115a005aecd1a656671806e78a2e3f6b8856b346"
  safeAddress: "0x7C8B6c46bc4F405B343B8Af753a3C3edB387F6b3"
  moduleAddress: "0x27FcB5d6df51fC067fC2FbC1155bC0C70dE77c35"
