---
apiVersion: hoprnet.org/v1alpha2
kind: IdentityHoprd
metadata:
  name: pull-requests-dufour-4
  namespace: dufour
spec:
  identityPoolName: pull-requests-dufour
  identityFile: "eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiIyYmE0ZWRkZWViMDI3MThhNmU0YzlhYjE3NDM1Y2FmOCJ9LCJjaXBoZXJ0ZXh0IjoiN2JhOGEwOGJjMjQyMGNjNTQ1YjM5MDc3N2YzZjJjOWE3NzZhNjkwZDljMDg1OWE3MDFmZGY0N2E5MDE5OWUwZWQ5ZGFjYzA2MmU3OTkxNWY1NTU0ODkwMzYwNTUwMTQ3MmZhODA5NmEzNjlkNTYzMWQ4N2IxZGQ1YWEwZWRiYTdiMzQ1ZTkyMDBkZTRmNjlmMGJmMGVjMGZiMThlNmJjYjhlZjgxZDdjM2QzMmM3MThiMDU2YjM3YTZlYWU3Y2VlZGJmZDMwNGRlYTFiZmZmNWQ5NDU2NDdlZjExOTM4MWEzMzk1OWNjNzhlNzc5ZTM3MWQ4Yzk2NmE5MzYyMjY0NmQ1NzA0ZjUwMjBiODdkNjhiZTE5MmY5M2MwYTNkYWZhNTkyZjJkYTE0ZjkxYzhiZmFiYmZiYzgyNmIyMThkY2NjNzVkMDA3NTVkY2YzNTY2Mzk5ZjExNWEiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiNGY4OWU2ZTczZmJjNzY4NDQ3NjhlZjgzNTdlOWM5ZTI2NDQ5MDcwYjYzYThjZmE3NmFiODg2N2EwMTMyNWU1NSJ9LCJtYWMiOiJlM2M5ZTdiMjRiMzhhNmZkZTkxOWViNDExOWZkYTViNzFhZmI5NzYwZWQwN2RjNjAyZTE2YTE1ZjIyMDcxNTJjIn0sImlkIjoiYWRjNTI5NjktNGZiZi00YTVmLTgyYWUtZjA1N2U3YTYyMGI0IiwidmVyc2lvbiI6M30="
  peerId: "12D3KooWRvkXaiogDRCyWpdDaDiRm5ixTjDfd4f3RpS1behRdBS5"
  nativeAddress: "0x7d852faebb35adaed925869e028d9325bdd555a4"
  safeAddress: "0x7C8B6c46bc4F405B343B8Af753a3C3edB387F6b3"
  moduleAddress: "0x27FcB5d6df51fC067fC2FbC1155bC0C70dE77c35"
