---
apiVersion: hoprnet.org/v1alpha2
kind: IdentityHoprd
metadata:
  name: pull-requests-dufour-6
  namespace: core-team
spec:
  identityPoolName: pull-requests-dufour
  identityFile: eyJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJjZGNkOGIzMjgyMjA1ZGI2ZTVkMzI1NDBkZGQ1OWQ2YyJ9LCJjaXBoZXJ0ZXh0IjoiZGI2NDNkMmVkMGQ4M2ZjNmI4NDhiZDM0YzFjOTc3ZjIyYzA4NTE3YTg5OGE1OTRjMzljZDk0NWNhMjBhMzk2MGEyODg5ODdjNWQ4YTRkZjFlMTFmYzkxYzYxMTBjODBhZmU1NDZiNGVhMjc3NTM2MGE3MzA3MTIzNzU0NGQwMDg1MWFmZDM2ODBmZmU5MTQzODM4MjQ0YjNkYzYwMTE2OTAzODlkYTRlNzE5ZTFmY2E4MzZmODFiYWQ5OWIyMDcyNDA1NmU3ZDUyODA2YmQyNDRmN2UwZTc2NWI2OTcyYThjN2RkN2E1ZjU4YzhjMTQxNDhjNzYyZDdiZWE1ODYzZTlmZWM1NTU1ZTkyYzUwYmFiNzk4NjExZDEzM2JmN2QwZGNjZTUwOGI0ZTYwMmQyODg2ODg0NjI2Zjc5YWE1ZjA0ZTNiMzY4NjcwZjg5Zjk4NmY2ZWU0NDgiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJuIjo4MTkyLCJwIjoxLCJyIjo4LCJzYWx0IjoiMmRjYTU2NDdhNDlhZjEyYmVjYmM5ZmJkODMwMzY5NjUyMzFkMTZhNWU4MWI5NjlkMDUyZTUzNjczNzY4NDZhMyJ9LCJtYWMiOiIzZTMzMjMxYTZhMDA4NDU5ZDY2YjM0MjUwNWI2NjkxOGNjMzJkZmI4MTQ1OGYwNWY4NjcwMjEyZGI1MGExMmIxIn0sImlkIjoiOWUzYmFmMmUtYmM3ZS00MmE4LTg4Y2ItYzg1Mzc0MWM1MDUzIiwidmVyc2lvbiI6M30=
  peerId: "12D3KooWEGsA96TbAq2wBr2SNczYzowBAVCLKm6mUX5auGrLeMNi"
  nativeAddress: "0x074230a241762e09b63d40a5fc7578bfe1147bb7"
  safeAddress: "0x4AB5d02cfa5841aF9e30096c10179996841D9309"
  moduleAddress: "0xf83Ca2fC3A10Cefd400E59a00E2C934cb5893541"