---
apiVersion: hoprnet.org/v1alpha2
kind: ClusterHoprd
metadata:
  name: hoprd-node-2-1-0-rc-3-pr-6104
  labels:
    hoprds.hoprnet.org/pullRequest: "2.1.0-rc.3-pr.6104"
  namespace:  core-team
spec:
  identityPoolName: pull-requests-rotsee
  replicas: 1
  version: 2.1.0-rc.3-pr.6104
  supportedRelease: saint-louis
  enabled: true
  deployment:
    env: |
      - name: RUST_BACKTRACE
        value: full
      - name: RUST_LOG
        value: debug
      - name: OPENTELEMETRY_COLLECTOR_URL
        value: http://tempo-distributor.monitoring.svc:4318
  config: |
    hopr:
      chain:
        network: rotsee
        provider: https://gnosis-chain.rpc.rank1.co
