---
apiVersion: hoprnet.org/v1alpha2
kind: ClusterHoprd
metadata:
  name: hoprd-node-2-1-2-pr-6354
  labels:
    hoprds.hoprnet.org/pullRequest: "2.1.2-pr.6354"
  namespace:  core-team
spec:
  identityPoolName: pull-requests-dufour
  replicas: 1
  version: 2.1.2-pr.6354
  supportedRelease: saint-louis
  enabled: true
  config: |
    hopr:
      chain:
        network: dufour
        provider: http://gnosis-rpc-provider.rpc-provider.svc.cluster.local:8545

