---
apiVersion: hoprnet.org/v1alpha2
kind: ClusterHoprd
metadata:
  name: hoprd-node-2-2-0-rc-1-pr-6550
  labels:
    hoprds.hoprnet.org/pullRequest: "2.2.0-rc.1-pr.6550"
  namespace:  core-team
spec:
  identityPoolName: pull-requests-rotsee
  replicas: 1
  version: 2.2.0-rc.1-pr.6550
  supportedRelease: saint-louis
  enabled: true
  config: |
    hopr:
      chain:
        network: rotsee
        provider: https://gnosis.rpc-provider.prod.hoprnet.link
  deployment:
    startupProbe: |
      failureThreshold: 800
      httpGet:
        path: /startedz
        port: 3001
        scheme: HTTP
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe: |
      failureThreshold: 800
      httpGet:
        path: /readyz
        port: 3001
        scheme: HTTP
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe: |
      failureThreshold: 3
      httpGet:
        path: /healthyz
        port: 3001
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5