---
apiVersion: hoprnet.org/v1alpha2
kind: ClusterHoprd
metadata:
  name: hoprd-node-2-2-0-rc-1-pr-6542
  labels:
    hoprds.hoprnet.org/pullRequest: "2.2.0-rc.1-pr.6542"
  namespace:  core-team
spec:
  identityPoolName: pull-requests-rotsee
  replicas: 1
  version: 2.2.0-rc.1-pr.6542
  supportedRelease: saint-louis
  enabled: true
  config: |
    hopr:
      chain:
        network: rotsee
        provider: https://gnosis.rpc-provider.prod.hoprnet.link
