environments:
  staging:
    values:
      - values-common.yaml
      - values-rotsee.yaml
      - values-dufour.yaml
      - values-staging.yaml
    secrets:
      - secrets.sops.yaml
---
repositories:
 - name: hoprassociation
   url: europe-west3-docker.pkg.dev/hoprassociation/helm-charts
   oci: true
releases:
- name: core-nodes-ci
  namespace: core-team
  condition: ci.enabled
  chart: ./ci
  values:
    - values-{{ .Environment.Name }}.yaml
- name: core-nodes-pull-requests
  namespace: core-team
  condition: pull-requests.enabled
  chart: ./pull-requests
  values:
    - values-{{ .Environment.Name }}.yaml
- name: core-nodes-team
  namespace: core-team
  condition: team.enabled
  chart: ./team
  values:
    - values-{{ .Environment.Name }}.yaml
- name: hoprd-core-rotsee
  namespace: core-team
  condition: rotsee.enabled
  chart: hoprassociation/cluster-hoprd
  version: 0.3.1
  wait: true
  timeout: 5
  values:
    - values-common.yaml
    - values-rotsee.yaml
    - values-{{ .Environment.Name }}.yaml
  secrets:
    - secrets.sops.yaml
- name: hoprd-core-dufour
  namespace: core-team
  condition: dufour.enabled
  chart: hoprassociation/cluster-hoprd
  version: 0.3.1
  wait: true
  timeout: 5
  values:
    - values-common.yaml
    - values-dufour.yaml
    - values-{{ .Environment.Name }}.yaml
  secrets:
    - secrets.sops.yaml

