environments:
  staging:
    values:
      - values-common.yaml
      - values-staging.yaml
    secrets:
      - secrets.sops.yaml
  prod:
    values:
      - values-common.yaml
      - values-prod.yaml
    secrets:
      - secrets.sops.yaml
---
repositories:
 - name: hoprassociation
   url: europe-west3-docker.pkg.dev/hoprassociation/helm-charts
   oci: true
releases:
- name: core-nodes-ci
  namespace: core-team
  condition: ci.enabled
  chart: ./ci
  values:
    - values-{{ .Environment.Name }}.yaml
- name: core-nodes-pull-requests
  namespace: core-team
  condition: pull-requests.enabled
  chart: ./pull-requests
  values:
    - values-{{ .Environment.Name }}.yaml
- name: core-node
  namespace: core-team
  chart: hoprassociation/cluster-hoprd
  version: 0.3.4
  wait: true
  timeout: 5
  values:
    - values-common.yaml
    - values-{{ .Environment.Name }}.yaml
  secrets:
    - secrets.sops.yaml
