deployment:
  resources: |
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi
  startupProbe: |
    failureThreshold: 800
    httpGet:
      path: /startedz
      port: 3001
      scheme: HTTP
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe: |
    failureThreshold: 800
    httpGet:
      path: /readyz
      port: 3001
      scheme: HTTP
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 5
  livenessProbe: |
    failureThreshold: 3
    httpGet:
      path: /healthyz
      port: 3001
      scheme: HTTP
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
  env: |
    - name: RUST_BACKTRACE
      value: full
    - name: RUST_LOG
      value: info
    - name: HOPRD_OPENTELEMETRY_COLLECTOR_URL
      value: http://tempo-distributor.monitoring.svc:4318
identityPool:
  funding:
    enabled: false
    schedule: 30 1 * * 1
    nativeAmount: 1
